baseURL: "vitornegromonte.github.io/" 
title: Vitor Negromonte
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 4
        - name: Papers
          url: papers/
          weight: 4 
        - name: Blog
          url: https://medium.com/@vitornegromonte
          weight: 4

params:
    description: "Data Scientist and AI Researcher"
    author: Vitor Negromonte
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","papers", "blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Vitor Negromonte
          subtitle: "Data Scientist and AI Researcher. Undergraduate **Statistics** student at the Federal University of Pernambuco (UFPE) with a focus on **machine learning** and model **optimization**. Currently, conducting research in **Generative AI**, working on the evaluation and optimization of **Language Models (LLMs)** and **retrieval algorithms**. Passionate about data science, with hands-on experience in **Python**, **R**, machine learning frameworks, and AI-driven projects aimed at solving real-world problems."
          imageUrl: "profile.jpg"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://medium.com/@vitornegromonte

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:vitorncabral@gmail.com
        - name: GitHub
          url: https://github.com/vitornegromonte
        - name: LinkedIn
          url: https://linkedin.com/in/vitornegromonte
        - name: Instagram
          url: https://instagram.com/vitor.ncabral
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Vitor Negromonte"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2